//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParallelExecution
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParallelExecutionConfiguration
    {
        public System.Guid SessionId { get; set; }
        public int SessionStatus { get; set; }
        public int MaxDegreeOfParallelism { get; set; }
        public string PartitionStatement { get; set; }
        public string PartitionCommand { get; set; }
        public Nullable<System.DateTime> DraftDate { get; set; }
        public Nullable<System.DateTime> QueuedDate { get; set; }
        public Nullable<System.DateTime> ProcessingDate { get; set; }
        public Nullable<System.DateTime> FailedDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string Comments { get; set; }
    }
}
